# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: crash_monkey 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "crash_monkey"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ken Morishita"]
  s.date = "2016-10-04"
  s.description = "This is a Monkey Test Tool using UIAutomation."
  s.email = "mokemokechicken@gmail.com"
  s.executables = ["crash_monkey"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "README_jp.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "README_jp.md",
    "Rakefile",
    "VERSION",
    "bin/crash_monkey",
    "crash_monkey.gemspec",
    "example_config.json",
    "lib/bootstrap/css/bootstrap-responsive.css",
    "lib/bootstrap/css/bootstrap-responsive.min.css",
    "lib/bootstrap/css/bootstrap.css",
    "lib/bootstrap/css/bootstrap.min.css",
    "lib/bootstrap/img/glyphicons-halflings-white.png",
    "lib/bootstrap/img/glyphicons-halflings.png",
    "lib/bootstrap/js/bootstrap.js",
    "lib/bootstrap/js/bootstrap.min.js",
    "lib/crash_monkey.rb",
    "lib/crash_monkey/command_helper.rb",
    "lib/crash_monkey/monkey_runner.rb",
    "lib/crash_monkey/templates/config.json",
    "lib/crash_monkey/templates/index.html.erb",
    "lib/crash_monkey/templates/result.html.erb",
    "lib/crash_monkey/templates/result_view.coffee",
    "lib/crash_monkey/templates/result_view.js",
    "lib/ui-auto-monkey/LICENSE",
    "lib/ui-auto-monkey/README.md",
    "lib/ui-auto-monkey/UIAutoMonkey.js",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/mokemokechicken/CrashMonkey"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Monkey Test For iOS Application"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>, [">= 2.7.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.7.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.8.2"])
    else
      s.add_dependency(%q<erubis>, [">= 2.7.0"])
      s.add_dependency(%q<json>, [">= 1.7.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.8.2"])
    end
  else
    s.add_dependency(%q<erubis>, [">= 2.7.0"])
    s.add_dependency(%q<json>, [">= 1.7.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.8.2"])
  end
end

